USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE PROCEDURE CLIENT_DATA_PLATFORM.METADATA.SP_LOAD_INITIAL_ORDERS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    rows_loaded NUMBER;
BEGIN

    TRUNCATE TABLE CLIENT_DATA_PLATFORM.RAW.ORDERS;

    INSERT INTO CLIENT_DATA_PLATFORM.RAW.ORDERS (
        ORDER_ID,
        CUSTOMER_ID,
        PRODUCT_CODE,
        ORDER_DATE,
        QUANTITY,
        UNIT_PRICE,
        TOTAL_AMOUNT,
        STATUS,
        CREATED_AT,
        UPDATED_AT
    )
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        PRODUCT_CODE,
        ORDER_DATE,
        QUANTITY,
        UNIT_PRICE,
        TOTAL_AMOUNT,
        STATUS,
        CREATED_AT,
        UPDATED_AT
    FROM ERP_PROVIDER_DB.SHARE.ORDERS;

    SELECT COUNT(*)
      INTO :rows_loaded
    FROM CLIENT_DATA_PLATFORM.RAW.ORDERS;

    RETURN 'INITIAL LOAD COMPLETED | ROWS = ' || rows_loaded;

END;
$$;