
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE PROCEDURE CLIENT_DATA_PLATFORM.METADATA.SP_LOAD_INITIAL_ORDERS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    rows_loaded NUMBER;
BEGIN

    TRUNCATE TABLE CLIENT_DATA_PLATFORM.RAW.ORDERS;

    INSERT INTO CLIENT_DATA_PLATFORM.RAW.ORDERS
    SELECT *
    FROM ERP_PROVIDER_DB.SHARE.ORDERS;

    rows_loaded := (SELECT COUNT(*) FROM CLIENT_DATA_PLATFORM.RAW.ORDERS);

    RETURN 'INITIAL LOAD COMPLETED | ROWS = ' || rows_loaded;

END;
$$;