-- ==========================================================
-- EL AZURE DATA PLATFORM
-- SNOWFLAKE BOOTSTRAP
-- ==========================================================

USE ROLE ACCOUNTADMIN;

-- ==========================================================
-- WAREHOUSE
-- ==========================================================

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse used by the Enterprise EL Platform POC'    
    ;

-- ==========================================================
-- DATABASE
-- ==========================================================

--CREATE DATABASE IF NOT EXISTS CLIENT_DATA_PLATFORM
--COMMENT = 'Client Data Platform';

--USE DATABASE CLIENT_DATA_PLATFORM;

-- ==========================================================
-- SCHEMAS
-- ==========================================================

--CREATE SCHEMA IF NOT EXISTS RAW;
--CREATE SCHEMA IF NOT EXISTS STAGING;
--CREATE SCHEMA IF NOT EXISTS ANALYTICS;
--CREATE SCHEMA IF NOT EXISTS METADATA;

-- ==========================================================
-- ROLE
-- ==========================================================

--CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE
--COMMENT = 'Role used by dbt';

-- ==========================================================
-- USER
-- ==========================================================

CREATE USER IF NOT EXISTS DW0SNW0DBT
    PASSWORD='Sabote.123.123'
    DEFAULT_ROLE=TRANSFORMER_ROLE
    DEFAULT_WAREHOUSE=COMPUTE_WH
    DEFAULT_NAMESPACE=CLIENT_DATA_PLATFORM.METADATA
    MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE TRANSFORMER_ROLE TO USER DW0SNW0DBT;

-- ==========================================================
-- WAREHOUSE
-- ==========================================================

GRANT USAGE
ON WAREHOUSE COMPUTE_WH
TO ROLE TRANSFORMER_ROLE;

GRANT OPERATE
ON WAREHOUSE COMPUTE_WH
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- DATABASE
-- ==========================================================

GRANT USAGE
ON DATABASE CLIENT_DATA_PLATFORM
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- SCHEMAS
-- ==========================================================

GRANT USAGE
ON SCHEMA CLIENT_DATA_PLATFORM.RAW
TO ROLE TRANSFORMER_ROLE;

GRANT USAGE
ON SCHEMA CLIENT_DATA_PLATFORM.STAGING
TO ROLE TRANSFORMER_ROLE;

GRANT USAGE
ON SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT USAGE
ON SCHEMA CLIENT_DATA_PLATFORM.METADATA
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- CREATE PRIVILEGES
-- ==========================================================

GRANT CREATE TABLE
ON SCHEMA CLIENT_DATA_PLATFORM.RAW
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE VIEW
ON SCHEMA CLIENT_DATA_PLATFORM.STAGING
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE TABLE
ON SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE VIEW
ON SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE STAGE
ON SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE FILE FORMAT
ON SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE PROCEDURE
ON SCHEMA CLIENT_DATA_PLATFORM.METADATA
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- TABLE PRIVILEGES
-- ==========================================================

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA CLIENT_DATA_PLATFORM.RAW
TO ROLE TRANSFORMER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA CLIENT_DATA_PLATFORM.RAW
TO ROLE TRANSFORMER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;
-- ==========================================================
-- SCHEMAS
-- ==========================================================

GRANT CREATE TABLE
ON SCHEMA CLIENT_DATA_PLATFORM.RAW
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE TABLE
ON SCHEMA CLIENT_DATA_PLATFORM.CORE
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE VIEW
ON SCHEMA CLIENT_DATA_PLATFORM.CORE
TO ROLE TRANSFORMER_ROLE;

GRANT CREATE TABLE
ON SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;


-- ==========================================================
-- VIEWS
-- ==========================================================

GRANT SELECT
ON ALL VIEWS IN SCHEMA CLIENT_DATA_PLATFORM.STAGING
TO ROLE TRANSFORMER_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA CLIENT_DATA_PLATFORM.STAGING
TO ROLE TRANSFORMER_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- PROCEDURES
-- ==========================================================

GRANT USAGE
ON ALL PROCEDURES IN SCHEMA CLIENT_DATA_PLATFORM.METADATA
TO ROLE TRANSFORMER_ROLE;

GRANT USAGE
ON FUTURE PROCEDURES IN SCHEMA CLIENT_DATA_PLATFORM.METADATA
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- RAW TABLE OWNER
-- ==========================================================

GRANT OWNERSHIP
ON ALL TABLES IN SCHEMA CLIENT_DATA_PLATFORM.RAW
TO ROLE TRANSFORMER_ROLE
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON FUTURE TABLES IN SCHEMA CLIENT_DATA_PLATFORM.RAW
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- ANALYTICS OWNER
-- ==========================================================

GRANT OWNERSHIP
ON ALL TABLES IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON FUTURE TABLES IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

GRANT OWNERSHIP
ON ALL VIEWS IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON FUTURE VIEWS IN SCHEMA CLIENT_DATA_PLATFORM.ANALYTICS
TO ROLE TRANSFORMER_ROLE;

-- ==========================================================
-- DEFAULT ROLE
-- ==========================================================

ALTER USER DW0SNW0DBT
SET DEFAULT_ROLE = TRANSFORMER_ROLE;

ALTER USER DW0SNW0DBT
SET DEFAULT_WAREHOUSE = COMPUTE_WH;

ALTER USER DW0SNW0DBT
SET DEFAULT_NAMESPACE = CLIENT_DATA_PLATFORM.METADATA;

-- ==========================================================
-- DONE
-- ==========================================================

SELECT CURRENT_ROLE();      -- ACCOUNTADMIN
SELECT CURRENT_DATABASE();  -- CLIENT_DATA_PLATFORM
SELECT CURRENT_WAREHOUSE(); -- COMPUTE_WH


GRANT ROLE TRANSFORMER_ROLE TO USER dw0snw0dbt;
GRANT ROLE AIRFLOW_ROLE TO USER dw0snw0dbt;


------------------------------------------------------
-- Snowflake Tasks
------------------------------------------------------

ALTER TASK CLIENT_DATA_PLATFORM.METADATA.TASK_INCREMENTAL_ORDERS RESUME;