el_azure_dbt:

  target: dev

  outputs:

    dev:
      type: snowflake

      account: 'your_account'
      user: 'user'
      password: 'pass'

      role: TRANSFORMER_ROLE
      warehouse: COMPUTE_WH
      database: CLIENT_DATA_PLATFORM
      schema: ANALYTICS

      threads: 2
      client_session_keep_alive: false
