USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

USE DATABASE CLIENT_DATA_PLATFORM;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CLIENT_DATA_PLATFORM.RAW.ORDERS
(
    ORDER_ID        NUMBER,
    CUSTOMER_ID     NUMBER,
    PRODUCT_CODE    VARCHAR,

    ORDER_DATE      DATE,

    QUANTITY        NUMBER,

    UNIT_PRICE      NUMBER(10,2),

    TOTAL_AMOUNT    NUMBER(12,2),

    STATUS          VARCHAR,

    CREATED_AT      TIMESTAMP_NTZ,

    UPDATED_AT      TIMESTAMP_NTZ
);