USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

USE DATABASE MONITORING_DB;
USE SCHEMA PIPELINE;

CREATE OR REPLACE TABLE PIPELINE_EXECUTION_LOG
(
    EXECUTION_ID      NUMBER AUTOINCREMENT,

    PIPELINE_NAME     STRING,

    TABLE_NAME        STRING,

    LOAD_TYPE         STRING,

    START_TIME        TIMESTAMP_NTZ,

    END_TIME          TIMESTAMP_NTZ,

    STATUS            STRING,

    ROWS_PROCESSED    NUMBER,

    ERROR_MESSAGE     STRING,

    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);