CREATE OR REPLACE TASK CLIENT_DATA_PLATFORM.METADATA.TASK_PIPELINE_START
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS

INSERT INTO MONITORING_DB.PIPELINE.PIPELINE_EXECUTION_LOG
(
    PIPELINE_NAME,
    TABLE_NAME,
    LOAD_TYPE,
    START_TIME,
    STATUS
)
VALUES
(
    'ERP_EL_PIPELINE',
    'ALL_TABLES',
    'INCREMENTAL',
    CURRENT_TIMESTAMP(),
    'STARTED'
);