USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TASK TASK_INCREMENTAL_ORDERS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'

AS

CALL CLIENT_DATA_PLATFORM.METADATA.SP_LOAD_INCREMENTAL_ORDERS();