CREATE OR REPLACE TASK CLIENT_DATA_PLATFORM.METADATA.TASK_INCREMENTAL_ORDERS

AFTER CLIENT_DATA_PLATFORM.METADATA.TASK_PIPELINE_START

AS

MERGE INTO CLIENT_DATA_PLATFORM.RAW.ORDERS T
USING ERP_PROVIDER_DB.SHARE.ORDERS S

ON T.ORDER_ID = S.ORDER_ID

WHEN MATCHED
AND S.UPDATED_AT > T.UPDATED_AT

THEN UPDATE SET

CUSTOMER_ID = S.CUSTOMER_ID,
PRODUCT_CODE = S.PRODUCT_CODE,
ORDER_DATE = S.ORDER_DATE,
QUANTITY = S.QUANTITY,
UNIT_PRICE = S.UNIT_PRICE,
TOTAL_AMOUNT = S.TOTAL_AMOUNT,
STATUS = S.STATUS,
UPDATED_AT = S.UPDATED_AT

WHEN NOT MATCHED THEN

INSERT
(
ORDER_ID,
CUSTOMER_ID,
PRODUCT_CODE,
ORDER_DATE,
QUANTITY,
UNIT_PRICE,
TOTAL_AMOUNT,
STATUS,
CREATED_AT,
UPDATED_AT
)

VALUES
(
S.ORDER_ID,
S.CUSTOMER_ID,
S.PRODUCT_CODE,
S.ORDER_DATE,
S.QUANTITY,
S.UNIT_PRICE,
S.TOTAL_AMOUNT,
S.STATUS,
S.CREATED_AT,
S.UPDATED_AT
);