CREATE OR REPLACE TASK CLIENT_DATA_PLATFORM.METADATA.TASK_INCREMENTAL_CUSTOMERS

AFTER CLIENT_DATA_PLATFORM.METADATA.TASK_PIPELINE_START

AS

MERGE INTO CLIENT_DATA_PLATFORM.RAW.CUSTOMERS T

USING ERP_PROVIDER_DB.SHARE.CUSTOMERS S

ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED
AND S.UPDATED_AT > T.UPDATED_AT

THEN UPDATE SET

CUSTOMER_NAME = S.CUSTOMER_NAME,
EMAIL = S.EMAIL,
UPDATED_AT = S.UPDATED_AT

WHEN NOT MATCHED THEN

INSERT
(
CUSTOMER_ID,
CUSTOMER_NAME,
EMAIL,
CREATED_AT,
UPDATED_AT
)

VALUES
(
S.CUSTOMER_ID,
S.CUSTOMER_NAME,
S.EMAIL,
S.CREATED_AT,
S.UPDATED_AT
);