USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE TASK CLIENT_DATA_PLATFORM.METADATA.TASK_INCREMENTAL_ORDERS

WAREHOUSE = COMPUTE_WH

SCHEDULE = 'USING CRON 0 2 * * * UTC'

AS

MERGE INTO CLIENT_DATA_PLATFORM.RAW.ORDERS tgt

USING (

    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        PRODUCT_CODE,
        ORDER_DATE,
        QUANTITY,
        UNIT_PRICE,
        TOTAL_AMOUNT,
        STATUS,
        CREATED_AT,
        UPDATED_AT

    FROM ERP_PROVIDER_DB.SHARE.ORDERS

) src

ON tgt.ORDER_ID = src.ORDER_ID

WHEN MATCHED
AND src.UPDATED_AT > tgt.UPDATED_AT THEN

UPDATE SET

    CUSTOMER_ID = src.CUSTOMER_ID,
    PRODUCT_CODE = src.PRODUCT_CODE,
    ORDER_DATE = src.ORDER_DATE,
    QUANTITY = src.QUANTITY,
    UNIT_PRICE = src.UNIT_PRICE,
    TOTAL_AMOUNT = src.TOTAL_AMOUNT,
    STATUS = src.STATUS,
    CREATED_AT = src.CREATED_AT,
    UPDATED_AT = src.UPDATED_AT

WHEN NOT MATCHED THEN

INSERT (

    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_CODE,
    ORDER_DATE,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    STATUS,
    CREATED_AT,
    UPDATED_AT

)

VALUES (

    src.ORDER_ID,
    src.CUSTOMER_ID,
    src.PRODUCT_CODE,
    src.ORDER_DATE,
    src.QUANTITY,
    src.UNIT_PRICE,
    src.TOTAL_AMOUNT,
    src.STATUS,
    src.CREATED_AT,
    src.UPDATED_AT

);